POST http://localhost:3333/user
Content-Type: application/json

{
  "name": "João",
  "email": "teste@teste.com",
  "password": "123123"
}

###
POST http://localhost:3333/session
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123123"
}

###
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm_Do28iLCJlbWFpbCI6InRlc3RlQHRlc3RlLmNvbSIsImlhdCI6MTY5OTIxODk1MSwiZXhwIjoxNjk5ODIzNzUxLCJzdWIiOiI3NDczZGQzYi00YTQ4LTQ4OGEtOWUzNy1hNzZhZjY3NDU4ZTEifQ.IxxfQiMK2ikDTOMvdOPiy0CVNwqm0xytSANBNkPGTu0
