version: "3.1"

services:
  pq-barber:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "pg-barber"
    restart: always
    volumes:
      - ./bd-barber:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
