version: "3"

services:
  barber:
    image: postgres:alpine
    container_name: barber
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: barber
    ports:
      - 5432:5432
    volumes:
      - ./barber:/var/lib/postgresql/data
